package ddvote.shared; // CHANGED

import java.io.Serializable;

// Enum definition remains the same
public enum MessageType implements Serializable {
    REGISTER, LOGIN, GET_CANDIDATES, SUBMIT_VOTE, GET_RESULTS, PING, DISCONNECT,
    REGISTRATION_SUCCESS, REGISTRATION_FAILED, LOGIN_SUCCESS, LOGIN_FAILED, ALREADY_LOGGED_IN,
    CANDIDATE_LIST, VOTE_ACCEPTED, ALREADY_VOTED, VOTE_REJECTED, RESULTS_DATA,
    ELECTION_NOT_STARTED, ELECTION_RUNNING, ELECTION_FINISHED, PONG, SERVER_MESSAGE, ERROR,
    AUTHENTICATION_REQUIRED
}